# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :test do
    scan(
      scheme: "TestJenkinsDemo",
      devices: ["iPhone 16 Pro"],
      clean: true,
      output_directory: "./fastlane/test_output"
    )
  end

  desc "Build the app"
  lane :build do
    gym(
      scheme: "TestJenkinsDemo",
      export_method: "ad-hoc"
    )
  end

  desc "Deploy to TestFlight"
  lane :beta do
    increment_build_number
    build_app(
      scheme: "TestJenkinsDemo"
    )
    upload_to_testflight
  end

  desc "Upload to TestFlight"
  lane :upload_testflight do
    # Increment build number automatically
    increment_build_number(xcodeproj: "TestJenkinsDemo.xcworkspace")

    # App Store Connect API Key authentication (more secure)
    api_key = app_store_connect_api_key(
      key_id: "DKP8U2RZ6C",                  # Replace with your API Key ID
      issuer_id: "515a4881-da24-4e62-b978-0f897783ebb0",            # Replace with your Issuer ID
      key_filepath: "./fastlane/AuthKey_DKP8U2RZ6C.p8"  # Path to your API Key file
    )

    # Build the app
    build_app(
      workspace: "TestJenkinsDemo.xcworkspace",  # Use your workspace file
      scheme: "TestJenkinsDemo",
      export_method: "app-store",
      export_options: {
        compileBitcode: false,
        provisioningProfiles: {
          "com.vrinsoft.ioscicd" => "Virnsoft General App"  # Replace with actual profile
        }
      }
    )

    # Upload to TestFlight
    upload_to_testflight(
      api_key: api_key
    )
  end

  
end
